version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: 'radar-db'
    restart: always
    environment:
      MYSQL_DATABASE: 'radar'
      MYSQL_USER: 'radar_admin'
      MYSQL_PASSWORD: 'R4d4r_Adm1n'
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: 'R4d4r_R00t'
    ports:
      - 3307:3307
    healthcheck:
      test: ["CMD", 'mysql', '-u', 'root', '--password=R4d4r_R00t', '-e', 'USE radar;']
      retries: 3

  app:
    image: ghcr.io/go-hslu/weblab_project:latest # OR local -> build: .
    container_name: 'radar-app'
    environment:
      JWT_SECRET: 'S€crEt_PS5sst!'
      SERVER_HOST: 'localhost'
      SERVER_PORT: 8080
      DB_HOST: 'mysql'
      DB_PORT: 3307
      DB_NAME: 'radar'
      DB_USER: 'radar_admin'
      DB_PASSWORD: 'R4d4r_Adm1n' # TODO: Repalce with secret variables in repository -> ${MYSQL_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy # TODO: Why service_completed_successfully doesn't work? -> Ugly healthcheck temp fix