name: CI/CD (GitHub Container Registry)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: weblab_project

jobs:
  build:
    name: Build front- & backend and deploy Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup and use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path:  |
          radar-app/package-lock.json
          backend/package-lock.json

    - name: (Angular) Install dependencies
      run: npm install
      working-directory: radar-app

    - name: (Angular) Build application
      run: npm run build
      working-directory: radar-app

    - name: (Backend) Install dependencies
      run: npm install
      working-directory: backend

    - name: (Backend) Build application
      run: npm run build
      working-directory: backend

    - name: Push to GitHub Container Registry
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ env.REPOSITORY }}
        tags: latest
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
