name: build-ts-deploy-docker

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io

jobs:
  build-frontend:
    name: Build Angular frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup and use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'radar-app/package-lock.json'

    - name: (Angular) Install dependencies
      run: npm install
      working-directory: radar-app

    - name: (Angular) Build application
      run: npm run build
      working-directory: radar-app

  build-backend:
    name: Build backend
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup and use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'
        
    - name: (Backend) Install dependencies
      run: npm install
      working-directory: backend

    - name: (Backend) Build application
      run: npm run build
      working-directory: backend

  deploy:
    name: Create Docker image and push to GitHub Container Registry
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
    - name: Push to GitHub Container Registry
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: $${{ env.REGISTRY }}/${{ github.repository }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
