name: CI/CD (GitHub Pages)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build frontend and publish on gh-pages branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build Angular radar-app and deploy to gh-pages branch
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /weblab_project/
        deploy_branch: gh-pages
        angular_dist_build_folder: radar-app/dist/radar-app/browser
        angular_project_dir: radar-app
