name: Build frontend and deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Angular radar-app and deploy to gh-pages branch
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /weblab_project/
        deploy_branch: gh-pages
        angular_dist_build_folder: radar-app/dist/radar-app/browser
        angular_project_dir: radar-app

permissions:
  contents: write
