name: Documentation (PDF)

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'docs/images/**'
  workflow_dispatch:

jobs:
  md-to-pdf:
    name: Deploy documentation as PDF
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build PDF
      uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_path: README.md
        output_dir: output
        image_import: docs/images
        build_html: false
        table_of_contents: true
    
    - name: Deploy PDF
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: output
        overwrite: true
